# -*- coding: utf-8 -*-
"""Challenge Alura Agente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YkrY5xf-rLPGO2pExTE1_YpQoJITpRD
"""

!pip install google-generativeai PyPDF2 python-dotenv

from google.colab import userdata
GOOGLE_API_KEY = userdata.get('Challenge_Alura_Agente')

from google.colab import files
uploaded = files.upload()

import PyPDF2
import io

def extrair_texto_pdf(nome_arquivo):
    texto = ""
    # Se o arquivo for um objeto bytes (como de files.upload())
    if isinstance(uploaded[nome_arquivo], bytes):
        # Use io.BytesIO para tratar como um arquivo em memória
        arquivo_bytes = io.BytesIO(uploaded[nome_arquivo])
        leitor = PyPDF2.PdfReader(arquivo_bytes)
    else:
        # Caso contrário, trate como um caminho de arquivo
        with open(nome_arquivo, 'rb') as arquivo:
            leitor = PyPDF2.PdfReader(arquivo)

    for pagina in leitor.pages:
        texto += pagina.extract_text()
    return texto

# Lista para armazenar o texto de todos os PDFs
textos_dos_pdfs = []
nomes_dos_pdfs = []

# Itera sobre os arquivos carregados
for nome_arquivo_uploaded in uploaded.keys():
    try:
        texto_extraido = extrair_texto_pdf(nome_arquivo_uploaded)
        textos_dos_pdfs.append(texto_extraido)
        nomes_dos_pdfs.append(nome_arquivo_uploaded)
        print(f"PDF '{nome_arquivo_uploaded}' carregado! {len(texto_extraido)} caracteres extraídos.")
    except Exception as e:
        print(f"Erro ao processar o arquivo '{nome_arquivo_uploaded}': {e}")

# Você pode usar a lista 'textos_dos_pdfs' nas suas próximas etapas
# Por exemplo, para concatenar todo o texto:
todo_o_texto_dos_pdfs = "\n\n".join(textos_dos_pdfs)

# Ou, se o agente precisar acessar cada documento individualmente, a lista já estará pronta.

import google.generativeai as genai

genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel("models/gemini-flash-latest")

# Define um limite maior para o contexto, considerando múltiplos documentos
# Gemini 1.5 Flash tem uma janela de contexto de 1 milhão de tokens,
# então 500.000 caracteres é um limite seguro para a maioria dos casos.
MAX_CONTEXT_LENGTH = 500000

def perguntar_sobre_documento(pergunta):
    prompt = f"""
    Você é um assistente especializado em análise de documentos. Responda a pergunta abaixo
    baseando-se APENAS no conteúdo dos documentos fornecidos.

    DOCUMENTOS:
    {todo_o_texto_dos_pdfs[:MAX_CONTEXT_LENGTH]}

    PERGUNTA: {pergunta}

    INSTRUÇÕES:
    1. Responda de forma clara e direta
    2. Baseie sua resposta APENAS nos documentos fornecidos
    3. Se a resposta não estiver nos documentos, diga "Não encontrei essa informação nos documentos."
    4. Cite trechos dos documentos quando relevante
    """
    resposta = model.generate_content(prompt)
    return resposta.text

# Exemplo de uso:
# Vou fazer uma pergunta que pode abranger mais de um documento para testar a nova funcionalidade.
pergunta = "Quais são os principais tipos de análise de dados mencionados e o que é dito sobre recomendações de governança de IA?"
resposta = perguntar_sobre_documento(pergunta)
print("📝 Resposta:")
print(resposta)

print("💬 Faça perguntas sobre o PDF (digite 'sair' para encerrar)")
while True:
    pergunta = input("❓ Você: ")
    if pergunta.lower() == 'sair':
        print("👋 Até logo!")
        break
    print("\n🤔 Processando...")
    resposta = perguntar_sobre_documento(pergunta)
    print(f"\n✅ Resposta: {resposta}\n")
    print("-" * 50)

!pip install gradio

import gradio as gr
import time

# ============================================================
# CONFIGURAÇÃO OTIMIZADA
# ============================================================

# 1. Reduzir o contexto para acelerar
MAX_CONTEXT_LENGTH = 50000  # 50.000 caracteres (mais rápido)

# 2. Usar modelo mais rápido
model = genai.GenerativeModel("models/gemini-1.5-flash")

# ============================================================
# FUNÇÃO DE RESPOSTA COM FEEDBACK
# ============================================================

def responder_com_feedback(message, history):
    """
    Responde com feedback visual em etapas
    """
    try:
        # Etapa 1: Feedback imediato
        yield "⏳ Processando..."

        # Etapa 2: Verificação dos documentos
        if 'todo_o_texto_dos_pdfs' not in globals() or not todo_o_texto_dos_pdfs:
            yield "⚠️ Nenhum documento carregado. Faça upload de um PDF primeiro."
            return

        # Etapa 3: Indicador de progresso
        yield f"📚 Buscando nos documentos..."

        # Pequena pausa para o feedback visual
        time.sleep(0.3)

        # Etapa 4: Processa a pergunta
        resposta = perguntar_sobre_documento(message)

        # Etapa 5: Mostra a resposta
        yield resposta

    except NameError as e:
        yield f"❌ Erro: Função não definida. Detalhe: {e}"

    except Exception as e:
        yield f"❌ Erro: {str(e)}"

# ============================================================
# INTERFACE COM FEEDBACK
# ============================================================

tema_laranja = gr.themes.Soft(
    primary_hue="orange",
    secondary_hue="amber",
    neutral_hue="gray",
    font=gr.themes.GoogleFont("Inter"),
    text_size=gr.themes.sizes.text_md,
)

chat_interface = gr.ChatInterface(
    fn=responder_com_feedback,
    title="🤖 AI KNOWLEDGE ASSISTANT",
    description="""
    🚀 **Agente otimizado para velocidade!**

    **📚 Documentos disponíveis:**
    - Recomendações de Governança para IA no Poder Público
    - Manual de Inteligência Artificial
    - IA: Avanços e Tendências (USP)
    - Análise de Dados: Da Teoria à Prática

    **💡 Perguntas rápidas:**
    - O que a LGPD diz sobre decisões automatizadas?
    - O que é a ferramenta DISC?
    - Quais são os 4 tipos de análise de dados?
    """,
    examples=[
        "O que a LGPD diz sobre decisões automatizadas?",
        "O que é a ferramenta DISC e como ela é usada?",
        "Quais são os quatro tipos de análise de dados?",
        "Quais são os principais desafios éticos da Inteligência Artificial?",
        "Quais são os principais riscos do uso de IA no sistema judicial brasileiro?"
    ]
)

with gr.Blocks(theme=tema_laranja) as demo:
    gr.Markdown("""
    ### ⚡ Dica: Perguntas específicas são respondidas mais rápido!
    """)
    chat_interface.render()

demo.launch(share=True)

def responder(message, history):
    # Mostra que o agente está processando
    yield "🤔 Pensando..."

    # Processa a resposta
    resposta = responder_pergunta(message)

    # Mostra a resposta final
    yield resposta

def responder(message, history):
    # history contém o histórico de mensagens
    resposta = responder_pergunta(message)

    # Pode usar o histórico para contexto
    return resposta

import gradio as gr

# Interface com upload de arquivo
def processar_pdf(pergunta, arquivo):
    if arquivo is None:
        return "Por favor, faça upload de um PDF primeiro."

    # Lê o PDF
    import PyPDF2
    texto = ""
    with open(arquivo.name, 'rb') as f:
        leitor = PyPDF2.PdfReader(f)
        for pagina in leitor.pages:
            texto += pagina.extract_text()

    # Processa a pergunta
    model = genai.GenerativeModel("models/gemini-1.0-pro")
    prompt = f"DOCUMENTO: {texto[:15000]}\n\nPERGUNTA: {pergunta}"
    resposta = model.generate_content(prompt)
    return resposta.text

with gr.Blocks() as demo:
    gr.Markdown("AI KNOWLEDGE ASSISTANT")

    with gr.Row():
        with gr.Column():
            arquivo = gr.File(label="📄 Upload do PDF")
            pergunta = gr.Textbox(label="❓ Sua pergunta", placeholder="Digite sua pergunta aqui...")
            botao = gr.Button("Enviar")
        with gr.Column():
            saida = gr.Textbox(label="✅ Resposta", lines=10)

    botao.click(processar_pdf, inputs=[pergunta, arquivo], outputs=saida)

demo.launch(share=True)