# -*- coding: utf-8 -*-
"""Challenge_Alura_Agente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-OvNvMooEZvO3nJZovKkVe9bSZM-qSRJ
"""

# Execute esta instalação em uma célula separada no Google Colab:
!pip install -q -U gradio faiss-cpu sentence-transformers pypdf python-docx google-genai

# ============================================================
# AGENTE ALURA — RAG PERSISTENTE COM GRADIO + GEMINI
# ============================================================

from google.colab import userdata, drive
from google import genai
import gradio as gr
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from pypdf import PdfReader
from docx import Document
from pathlib import Path
import hashlib
import json
import os
import pickle
import shutil
import threading
import time

# ------------------------------------------------------------
# 1. CONFIGURAÇÃO
# ------------------------------------------------------------

# Monte o Google Drive para manter a base entre sessões do Colab.
drive.mount("/content/drive", force_remount=False)

BASE_DIR = Path("/content/drive/MyDrive/alura_agente_base")
ARQUIVOS_DIR = BASE_DIR / "arquivos"
PASTA_DOCUMENTOS_DRIVE = Path("/content/drive/MyDrive/Agente_Alura_Documentos")
CHUNKS_PATH = BASE_DIR / "chunks.pkl"
METADADOS_PATH = BASE_DIR / "metadados.json"
INDEX_PATH = BASE_DIR / "indice.faiss"

BASE_DIR.mkdir(parents=True, exist_ok=True)
ARQUIVOS_DIR.mkdir(parents=True, exist_ok=True)
PASTA_DOCUMENTOS_DRIVE.mkdir(parents=True, exist_ok=True)

# A chave deve ser criada em:
# Colab > ícone da chave > Secrets > GEMINI_API_KEY
try:
    API_KEY = userdata.get("ALURA_AGENTE_API_KEY")
except Exception as exc:
    raise RuntimeError(
        "Crie o Secret GEMINI_API_KEY no Google Colab antes de executar."
    ) from exc

if not API_KEY:
    raise RuntimeError("O Secret GEMINI_API_KEY está vazio.")

client = genai.Client(api_key=API_KEY)

# Primeiro tenta modelos atuais; caso a conta não tenha acesso, usa fallback.
MODELOS_GEMINI = [
    "gemini-3.6-flash",
    "gemini-3.5-flash",
    "gemini-2.5-flash",
]

embedding_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)
DIMENSAO = embedding_model.get_sentence_embedding_dimension()

lock = threading.RLock()

# Estado global da base durante a sessão.
todos_chunks = []
metadados_chunks = []
index = faiss.IndexFlatIP(DIMENSAO)


# ------------------------------------------------------------
# 2. EXTRAÇÃO DE TEXTO
# ------------------------------------------------------------

def hash_arquivo(caminho: str) -> str:
    """Calcula um hash para impedir a duplicação do mesmo arquivo."""
    sha = hashlib.sha256()
    with open(caminho, "rb") as arquivo:
        for bloco in iter(lambda: arquivo.read(1024 * 1024), b""):
            sha.update(bloco)
    return sha.hexdigest()


def extrair_texto(caminho: str) -> str:
    """Extrai texto de PDF, TXT, Markdown e DOCX."""
    caminho_obj = Path(caminho)
    extensao = caminho_obj.suffix.lower()

    if extensao == ".pdf":
        leitor = PdfReader(str(caminho_obj))
        partes = []
        for numero, pagina in enumerate(leitor.pages, start=1):
            texto = pagina.extract_text() or ""
            if texto.strip():
                partes.append(f"[Página {numero}]\n{texto}")
        return "\n\n".join(partes)

    if extensao in {".txt", ".md"}:
        for encoding in ("utf-8", "latin-1"):
            try:
                return caminho_obj.read_text(encoding=encoding)
            except UnicodeDecodeError:
                continue
        raise ValueError(f"Não foi possível identificar a codificação de {caminho_obj.name}.")

    if extensao == ".docx":
        documento = Document(str(caminho_obj))
        return "\n".join(
            paragrafo.text for paragrafo in documento.paragraphs
            if paragrafo.text.strip()
        )

    raise ValueError(
        f"Formato não suportado: {extensao}. Use PDF, TXT, MD ou DOCX."
    )


def criar_chunks(texto: str, tamanho: int = 450, sobreposicao: int = 80):
    """
    Divide por palavras. Chunks menores melhoram a precisão da recuperação.
    """
    palavras = texto.split()
    if not palavras:
        return []

    passo = max(1, tamanho - sobreposicao)
    return [
        " ".join(palavras[inicio:inicio + tamanho])
        for inicio in range(0, len(palavras), passo)
        if palavras[inicio:inicio + tamanho]
    ]


# ------------------------------------------------------------
# 3. PERSISTÊNCIA
# ------------------------------------------------------------

def salvar_base():
    """Salva índice, chunks e metadados no Google Drive."""
    with lock:
        with open(CHUNKS_PATH, "wb") as arquivo:
            pickle.dump(todos_chunks, arquivo)

        METADADOS_PATH.write_text(
            json.dumps(metadados_chunks, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        faiss.write_index(index, str(INDEX_PATH))


def carregar_base():
    """Carrega a base persistida; se houver inconsistência, reconstrói o índice."""
    global todos_chunks, metadados_chunks, index

    with lock:
        if CHUNKS_PATH.exists():
            with open(CHUNKS_PATH, "rb") as arquivo:
                todos_chunks = pickle.load(arquivo)
        else:
            todos_chunks = []

        if METADADOS_PATH.exists():
            metadados_chunks = json.loads(
                METADADOS_PATH.read_text(encoding="utf-8")
            )
        else:
            metadados_chunks = []

        if len(metadados_chunks) != len(todos_chunks):
            # Evita operar com base corrompida/incompleta.
            metadados_chunks = [
                {
                    "arquivo": "Documento sem metadados",
                    "hash": "",
                    "chunk": numero,
                }
                for numero in range(len(todos_chunks))
            ]

        if INDEX_PATH.exists():
            index_carregado = faiss.read_index(str(INDEX_PATH))
            if index_carregado.ntotal == len(todos_chunks):
                index = index_carregado
                return

        reconstruir_indice(salvar=False)


def reconstruir_indice(salvar: bool = True):
    """Recalcula os embeddings e reconstrói o FAISS."""
    global index

    with lock:
        novo_indice = faiss.IndexFlatIP(DIMENSAO)

        if todos_chunks:
            embeddings = embedding_model.encode(
                todos_chunks,
                normalize_embeddings=True,
                show_progress_bar=False,
            )
            embeddings = np.asarray(embeddings, dtype="float32")
            novo_indice.add(embeddings)

        index = novo_indice

        if salvar:
            salvar_base()


def hashes_existentes():
    return {
        item.get("hash")
        for item in metadados_chunks
        if item.get("hash")
    }


# ------------------------------------------------------------
# 4. ADIÇÃO DE NOVOS DOCUMENTOS
# ------------------------------------------------------------

def normalizar_lista_arquivos(arquivos):
    if arquivos is None:
        return []
    if isinstance(arquivos, (str, Path)):
        return [str(arquivos)]
    return [str(item) for item in arquivos]


def adicionar_documentos(arquivos):
    """
    Processa uploads feitos dentro do Gradio, acrescenta-os à base atual
    e salva tudo no Google Drive.
    """
    global todos_chunks, metadados_chunks

    caminhos = normalizar_lista_arquivos(arquivos)
    if not caminhos:
        return status_base("Nenhum arquivo selecionado.")

    adicionados = []
    ignorados = []
    erros = []
    novos_chunks = []
    novos_metadados = []
    hashes = hashes_existentes()

    for caminho in caminhos:
        nome = Path(caminho).name
        try:
            arquivo_hash = hash_arquivo(caminho)

            if arquivo_hash in hashes:
                ignorados.append(f"{nome} (já estava na base)")
                continue

            texto = extrair_texto(caminho)
            if not texto.strip():
                erros.append(f"{nome}: nenhum texto extraível")
                continue

            chunks = criar_chunks(texto)
            if not chunks:
                erros.append(f"{nome}: não gerou trechos")
                continue

            destino = ARQUIVOS_DIR / nome
            if destino.exists():
                destino = ARQUIVOS_DIR / f"{arquivo_hash[:8]}_{nome}"
            shutil.copy2(caminho, destino)

            for numero, chunk in enumerate(chunks, start=1):
                novos_chunks.append(chunk)
                novos_metadados.append(
                    {
                        "arquivo": nome,
                        "caminho_salvo": str(destino),
                        "hash": arquivo_hash,
                        "chunk": numero,
                    }
                )

            hashes.add(arquivo_hash)
            adicionados.append(f"{nome} ({len(chunks)} trechos)")

        except Exception as exc:
            erros.append(f"{nome}: {exc}")

    if novos_chunks:
        with lock:
            todos_chunks.extend(novos_chunks)
            metadados_chunks.extend(novos_metadados)

            embeddings = embedding_model.encode(
                novos_chunks,
                normalize_embeddings=True,
                show_progress_bar=False,
            )
            embeddings = np.asarray(embeddings, dtype="float32")
            index.add(embeddings)
            salvar_base()

    mensagens = []
    if adicionados:
        mensagens.append("✅ Adicionados: " + "; ".join(adicionados))
    if ignorados:
        mensagens.append("ℹ️ Ignorados: " + "; ".join(ignorados))
    if erros:
        mensagens.append("⚠️ Problemas: " + "; ".join(erros))

    return status_base("\n".join(mensagens))


def listar_documentos():
    nomes = []
    vistos = set()
    for item in metadados_chunks:
        nome = item.get("arquivo", "Sem nome")
        if nome not in vistos:
            vistos.add(nome)
            nomes.append(nome)
    return nomes


def status_base(mensagem: str = ""):
    documentos = listar_documentos()
    cabecalho = (
        f"**Base ativa:** {len(documentos)} documento(s), "
        f"{len(todos_chunks)} trecho(s) e {index.ntotal} vetor(es)."
    )

    lista = "\n".join(f"- {nome}" for nome in documentos)
    if not lista:
        lista = "- Nenhum documento carregado."

    partes = [cabecalho, lista]
    if mensagem:
        partes.insert(0, mensagem)
    return "\n\n".join(partes)



def resolver_pasta_drive(pasta_informada: str = "") -> Path:
    """
    Aceita:
    - caminho completo: /content/drive/MyDrive/minha_pasta
    - caminho relativo: Minha pasta/subpasta
    - vazio: usa MyDrive/Agente_Alura_Documentos
    """
    valor = (pasta_informada or "").strip()

    if not valor:
        pasta = PASTA_DOCUMENTOS_DRIVE
    else:
        pasta = Path(valor)
        if not pasta.is_absolute():
            pasta = Path("/content/drive/MyDrive") / pasta

    return pasta


def localizar_arquivos_na_pasta(pasta: Path):
    """Localiza recursivamente os formatos aceitos dentro da pasta."""
    extensoes = {".pdf", ".txt", ".md", ".docx"}

    if not pasta.exists():
        return []

    return sorted(
        str(caminho)
        for caminho in pasta.rglob("*")
        if caminho.is_file() and caminho.suffix.lower() in extensoes
    )


def importar_pasta_drive(pasta_informada: str = ""):
    """
    Importa os documentos de uma pasta já existente no Google Drive.
    Arquivos anteriormente indexados são ignorados pelo hash.
    """
    pasta = resolver_pasta_drive(pasta_informada)

    if not pasta.exists():
        return status_base(
            f"⚠️ A pasta não foi encontrada: `{pasta}`\n\n"
            "Confira o nome e confirme que o Google Drive foi montado."
        )

    arquivos = localizar_arquivos_na_pasta(pasta)

    if not arquivos:
        return status_base(
            f"⚠️ Nenhum PDF, TXT, MD ou DOCX foi encontrado em `{pasta}`."
        )

    resultado = adicionar_documentos(arquivos)
    return (
        f"📂 Pasta consultada: `{pasta}`\n\n"
        f"🔎 {len(arquivos)} arquivo(s) compatível(is) localizado(s).\n\n"
        f"{resultado}"
    )


def importar_pasta_padrao_automaticamente():
    """
    Na inicialização, importa o conteúdo da pasta padrão do Drive.
    Se estiver vazia, apenas mantém a base persistida já existente.
    """
    arquivos = localizar_arquivos_na_pasta(PASTA_DOCUMENTOS_DRIVE)
    if arquivos:
        return importar_pasta_drive(str(PASTA_DOCUMENTOS_DRIVE))
    return status_base(
        f"ℹ️ Pasta padrão pronta: `{PASTA_DOCUMENTOS_DRIVE}`. "
        "Coloque os documentos nela e clique em **Importar pasta do Drive**."
    )


# ------------------------------------------------------------
# 5. BUSCA SEMÂNTICA E GERAÇÃO
# ------------------------------------------------------------

def buscar_chunks_relevantes(pergunta: str, k: int = 5):
    with lock:
        if index.ntotal == 0:
            return []

        quantidade = min(k, index.ntotal)
        embedding = embedding_model.encode(
            [pergunta],
            normalize_embeddings=True,
            show_progress_bar=False,
        )
        embedding = np.asarray(embedding, dtype="float32")
        similaridades, indices = index.search(embedding, quantidade)

        resultados = []
        for posicao, indice_chunk in enumerate(indices[0]):
            if indice_chunk < 0:
                continue

            metadata = metadados_chunks[indice_chunk]
            resultados.append(
                {
                    "texto": todos_chunks[indice_chunk],
                    "arquivo": metadata.get("arquivo", "Documento"),
                    "chunk": metadata.get("chunk", indice_chunk + 1),
                    "similaridade": float(similaridades[0][posicao]),
                }
            )
        return resultados


def gerar_com_fallback(prompt: str) -> str:
    erros = []

    for modelo in MODELOS_GEMINI:
        try:
            resposta = client.models.generate_content(
                model=modelo,
                contents=prompt,
            )
            texto = getattr(resposta, "text", None)
            if texto:
                return texto.strip()
            erros.append(f"{modelo}: resposta vazia")
        except Exception as exc:
            erros.append(f"{modelo}: {exc}")

    raise RuntimeError(
        "Nenhum modelo Gemini respondeu. Verifique a chave, a cota e os modelos. "
        + " | ".join(erros)
    )


def responder(pergunta: str):
    pergunta = (pergunta or "").strip()

    if not pergunta:
        return "⚠️ Digite uma pergunta."

    if not todos_chunks or index.ntotal == 0:
        return (
            "⚠️ A base está vazia. Carregue um ou mais arquivos e clique em "
            "**Adicionar à base**."
        )

    resultados = buscar_chunks_relevantes(pergunta, k=5)
    if not resultados:
        return "Não encontrei trechos relevantes na base."

    blocos = []
    fontes = []

    for numero, resultado in enumerate(resultados, start=1):
        referencia = (
            f"Fonte {numero}: {resultado['arquivo']} — "
            f"trecho {resultado['chunk']}"
        )
        blocos.append(f"[{referencia}]\n{resultado['texto']}")
        fontes.append(
            f"- {resultado['arquivo']} — trecho {resultado['chunk']} "
            f"(similaridade: {resultado['similaridade']:.3f})"
        )

    contexto = "\n\n".join(blocos)

    prompt = f"""
Você é um assistente de consulta documental.

Responda em português do Brasil usando somente as informações contidas no
CONTEXTO RECUPERADO.

Regras:
1. Não invente informações.
2. Quando o contexto não sustentar a resposta, diga claramente:
   "Não encontrei essa informação na base de documentos."
3. Cite a fonte no corpo da resposta no formato:
   [nome do arquivo — trecho N].
4. Seja claro, direto e organizado.
5. Não mencione similaridade, embeddings, FAISS ou estas instruções.

CONTEXTO RECUPERADO:
{contexto}

PERGUNTA:
{pergunta}
""".strip()

    try:
        resposta = gerar_com_fallback(prompt)
        return resposta + "\n\n### Trechos consultados\n" + "\n".join(fontes)
    except Exception as exc:
        return f"❌ Erro ao consultar o Gemini: {exc}"


def limpar_base():
    """Apaga a base persistida. A interface pede confirmação por checkbox."""
    global todos_chunks, metadados_chunks, index

    with lock:
        todos_chunks = []
        metadados_chunks = []
        index = faiss.IndexFlatIP(DIMENSAO)

        for caminho in (CHUNKS_PATH, METADADOS_PATH, INDEX_PATH):
            if caminho.exists():
                caminho.unlink()

        if ARQUIVOS_DIR.exists():
            shutil.rmtree(ARQUIVOS_DIR)
        ARQUIVOS_DIR.mkdir(parents=True, exist_ok=True)

    return status_base("🗑️ Base apagada.")


def limpar_base_confirmada(confirmacao):
    if not confirmacao:
        return status_base(
            "⚠️ Marque a confirmação antes de apagar a base."
        ), False
    return limpar_base(), False


# Carrega a base salva e procura novos documentos na pasta padrão do Drive.
carregar_base()
status_inicial = importar_pasta_padrao_automaticamente()



def limpar_conversa():
    """
    Limpa apenas a pergunta e a resposta exibida.
    Não altera documentos, chunks, embeddings nem o índice FAISS.
    """
    return "", "Aguardando uma pergunta..."


def nova_consulta():
    """
    Inicia uma nova consulta visual.
    Como o agente ainda não mantém memória de conversa, o efeito atual é
    reiniciar pergunta e resposta sem alterar a base documental.
    """
    return "", "Nova consulta iniciada. Digite sua pergunta."


# ------------------------------------------------------------
# 6. INTERFACE GRADIO
# ------------------------------------------------------------

css = """
/* ==========================================================
   IDENTIDADE VISUAL ORIGINAL + CONTRASTE E LEGIBILIDADE
   ========================================================== */

:root {
    --ag-bg-deep: #0f0c29;
    --ag-bg-mid: #302b63;
    --ag-bg-end: #24243e;
    --ag-panel: rgba(18, 22, 49, 0.92);
    --ag-panel-soft: rgba(255, 255, 255, 0.075);
    --ag-border: rgba(255, 255, 255, 0.20);
    --ag-text: #f8fafc;
    --ag-text-soft: #dbe4f0;
    --ag-muted: #b7c3d4;
    --ag-orange: #f7971e;
    --ag-yellow: #ffd200;
    --ag-mint: #64ffda;
    --ag-danger: #ff8a8a;
}

/* Fundo principal */
.gradio-container {
    background: linear-gradient(
        135deg,
        var(--ag-bg-deep) 0%,
        var(--ag-bg-mid) 50%,
        var(--ag-bg-end) 100%
    ) !important;
    min-height: 100vh;
    color: var(--ag-text) !important;
}

/* Garante cor legível nos textos gerais */
.gradio-container,
.gradio-container p,
.gradio-container span,
.gradio-container label,
.gradio-container li,
.gradio-container strong,
.gradio-container em,
.gradio-container h1,
.gradio-container h2,
.gradio-container h3,
.gradio-container h4,
.gradio-container h5,
.gradio-container h6 {
    color: var(--ag-text) !important;
}

/* Cabeçalho */
.header {
    text-align: center;
    padding: 30px 0 18px 0;
    color: var(--ag-text);
}

.header-logo {
    width: 92px;
    height: 92px;
    margin: 0 auto 12px auto;
    display: block;
    color: #ffd900;
    filter:
        drop-shadow(0 0 5px rgba(255, 217, 0, 0.95))
        drop-shadow(0 0 16px rgba(255, 183, 0, 0.70))
        drop-shadow(0 0 28px rgba(255, 210, 0, 0.35));
}

.header-logo {
    position: relative;
    border-radius: 50%;
    background: radial-gradient(
        circle,
        rgba(255, 210, 0, 0.19) 0%,
        rgba(255, 210, 0, 0.08) 48%,
        rgba(255, 210, 0, 0.00) 72%
    );
}

.header-logo svg {
    width: 100%;
    height: 100%;
    display: block;
    overflow: visible;
}

.header h1 {
    font-size: 3rem;
    font-weight: 800;
    color: var(--ag-yellow) !important;
    -webkit-text-fill-color: var(--ag-yellow) !important;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    margin-bottom: 8px;
    text-shadow: 0 0 18px rgba(255, 210, 0, 0.16);
}

.header p {
    color: var(--ag-text-soft) !important;
    font-size: 1.08rem;
}

/* Painéis principais */
.panel {
    background: var(--ag-panel) !important;
    border: 1px solid var(--ag-border) !important;
    border-radius: 18px !important;
    padding: 18px !important;
    box-shadow: 0 12px 30px rgba(0, 0, 0, 0.18);
    backdrop-filter: blur(14px);
}

/* Blocos Markdown e resultado */
.gradio-container .prose,
.gradio-container .prose p,
.gradio-container .prose li,
.gradio-container .prose strong,
.gradio-container .prose code,
.gradio-container .markdown,
.gradio-container [data-testid="markdown"] {
    color: var(--ag-text-soft) !important;
}

.gradio-container .prose h1,
.gradio-container .prose h2,
.gradio-container .prose h3,
.gradio-container .prose h4 {
    color: var(--ag-text) !important;
}

.gradio-container .prose code {
    background: rgba(100, 255, 218, 0.11) !important;
    border: 1px solid rgba(100, 255, 218, 0.24) !important;
    border-radius: 6px;
    padding: 2px 6px;
}

.gradio-container .prose a {
    color: #8fffe7 !important;
    text-decoration: underline;
}

/* Campos de texto */
.gradio-container input,
.gradio-container textarea {
    background: rgba(6, 10, 30, 0.88) !important;
    color: var(--ag-text) !important;
    border: 1px solid rgba(255, 255, 255, 0.28) !important;
    border-radius: 12px !important;
    caret-color: var(--ag-yellow) !important;
}

.gradio-container input::placeholder,
.gradio-container textarea::placeholder {
    color: #aebbd0 !important;
    opacity: 1 !important;
}

.gradio-container input:focus,
.gradio-container textarea:focus {
    border-color: var(--ag-mint) !important;
    box-shadow: 0 0 0 2px rgba(100, 255, 218, 0.18) !important;
}

/* Labels e textos auxiliares dos componentes */
.gradio-container .block-info,
.gradio-container .info,
.gradio-container .secondary-wrap,
.gradio-container .wrap label,
.gradio-container .form > label,
.gradio-container label span {
    color: var(--ag-text-soft) !important;
}

/* Área de upload */
.gradio-container [data-testid="file"],
.gradio-container .file-preview,
.gradio-container .file-preview-holder,
.gradio-container .upload-container,
.gradio-container .wrap.svelte-1ipelgc,
.gradio-container .drop-zone {
    background: rgba(6, 10, 30, 0.66) !important;
    color: var(--ag-text) !important;
    border-color: rgba(255, 255, 255, 0.28) !important;
}

.gradio-container [data-testid="file"] svg,
.gradio-container .upload-container svg {
    color: var(--ag-mint) !important;
    fill: currentColor !important;
}

/* Botões */
.gradio-container button {
    color: var(--ag-text) !important;
    border: 1px solid rgba(255, 255, 255, 0.25) !important;
    font-weight: 650 !important;
}

.gradio-container button.primary {
    background: linear-gradient(
        135deg,
        var(--ag-orange),
        var(--ag-yellow)
    ) !important;
    color: #17132e !important;
    border: none !important;
}

.gradio-container button.primary span {
    color: #17132e !important;
}

.gradio-container button.secondary {
    background: rgba(100, 255, 218, 0.13) !important;
    color: #eafff9 !important;
    border-color: rgba(100, 255, 218, 0.42) !important;
}

.gradio-container button.secondary span {
    color: #eafff9 !important;
}

.gradio-container button.stop {
    background: rgba(185, 48, 64, 0.30) !important;
    color: #fff0f2 !important;
    border-color: rgba(255, 138, 138, 0.50) !important;
}

.gradio-container button:hover {
    filter: brightness(1.12);
    transform: translateY(-1px);
}

/* Checkbox */
.gradio-container input[type="checkbox"] {
    accent-color: var(--ag-orange);
}

.gradio-container .checkbox-container,
.gradio-container .checkbox-container span {
    color: var(--ag-text-soft) !important;
}

/* Exemplos */
.gradio-container .examples,
.gradio-container .examples table,
.gradio-container .examples tbody,
.gradio-container .examples tr,
.gradio-container .examples td,
.gradio-container .examples th {
    background: transparent !important;
    color: var(--ag-text-soft) !important;
    border-color: rgba(255, 255, 255, 0.16) !important;
}

.gradio-container .examples button {
    background: rgba(255, 255, 255, 0.08) !important;
    color: var(--ag-text) !important;
}

/* Scrollbar */
.gradio-container ::-webkit-scrollbar {
    width: 8px;
    height: 8px;
}

.gradio-container ::-webkit-scrollbar-track {
    background: rgba(255, 255, 255, 0.05);
}

.gradio-container ::-webkit-scrollbar-thumb {
    background: rgba(100, 255, 218, 0.42);
    border-radius: 10px;
}

/* Melhor adaptação para telas menores */
@media (max-width: 720px) {
    .header-logo {
        width: 76px;
        height: 76px;
    }

    .header h1 {
        font-size: 2.05rem;
        letter-spacing: 0.045em;
    }

    .panel {
        padding: 14px !important;
    }
}
"""

header_html = """
<div class="header">
    <div class="header-logo" aria-label="Símbolo amarelo de robô">
        <svg viewBox="0 0 120 120" role="img" aria-hidden="true">
            <g fill="none" stroke="#ffd900" stroke-width="9"
               stroke-linecap="round" stroke-linejoin="round">
                <!-- Antena -->
                <path d="M60 22V10"/>
                <circle cx="60" cy="8" r="4" fill="currentColor" stroke="none"/>

                <!-- Cabeça/símbolo sem rosto -->
                <rect x="28" y="24" width="64" height="48" rx="14"/>

                <!-- Conectores laterais -->
                <path d="M28 42H18v14h10"/>
                <path d="M92 42h10v14H92"/>

                <!-- Corpo tecnológico -->
                <path d="M42 76v10"/>
                <path d="M78 76v10"/>
                <rect x="35" y="86" width="50" height="24" rx="8"/>

                <!-- Circuito central abstrato, sem olhos ou boca -->
                <path d="M48 48h24"/>
                <path d="M60 48v12"/>
                <circle cx="60" cy="63" r="3" fill="currentColor" stroke="none"/>
            </g>
        </svg>
    </div>
    <h1>AI KNOWLEDGE ASSISTANT</h1>
    <p>Agente Inteligente Com Base Documental Persistente</p>
</div>
"""

with gr.Blocks(css=css, theme=gr.themes.Base(), title="AI Knowledge Assistant") as demo:
    gr.HTML(header_html)

    with gr.Row():
        with gr.Column(scale=1, min_width=330, elem_classes="panel"):
            gr.Markdown("## 📚 Base de documentos")

            gr.Markdown(
                "### Google Drive\n"
                "Pasta padrão: `Meu Drive/Agente_Alura_Documentos`"
            )

            pasta_drive = gr.Textbox(
                label="Pasta do Google Drive",
                value="Agente_Alura_Documentos",
                placeholder="Ex.: Agente_Alura_Documentos ou Projetos/Documentos",
            )

            importar_drive_btn = gr.Button(
                "📂 Importar pasta do Drive",
                variant="primary",
            )

            gr.Markdown("### Upload manual")

            arquivos_upload = gr.File(
                label="Selecione arquivos para acrescentar",
                file_types=[".pdf", ".txt", ".md", ".docx"],
                file_count="multiple",
                type="filepath",
            )

            adicionar_btn = gr.Button(
                "➕ Adicionar uploads à base",
                variant="secondary",
            )

            status = gr.Markdown(value=status_inicial)

            atualizar_btn = gr.Button("🔄 Atualizar status")

            gr.Markdown("---")
            confirmar_limpeza = gr.Checkbox(
                label="Confirmo que desejo apagar toda a base"
            )
            apagar_btn = gr.Button("🗑️ Apagar base", variant="stop")

        with gr.Column(scale=2, min_width=500, elem_classes="panel"):
            gr.Markdown("## 💬 Pergunte aos documentos")

            pergunta = gr.Textbox(
                label="Pergunta",
                placeholder="Ex.: Quais são os principais riscos descritos nos documentos?",
                lines=3,
            )

            with gr.Row():
                enviar_btn = gr.Button(
                    "🚀 Enviar pergunta",
                    variant="primary",
                    scale=2,
                )

                nova_consulta_btn = gr.Button(
                    "🗂️ Nova consulta",
                    variant="secondary",
                    scale=1,
                )

            with gr.Row():
                limpar_conversa_btn = gr.Button(
                    "🧹 Limpar conversa",
                    variant="secondary",
                    scale=1,
                )

                copiar_resposta_btn = gr.Button(
                    "📋 Copiar resposta",
                    variant="secondary",
                    scale=1,
                )

            saida = gr.Markdown(
                value="Aguardando uma pergunta...",
            )

            gr.Examples(
                examples=[
                    ["Quais são os principais temas tratados nos documentos?"],
                    ["Faça um resumo dos pontos mais importantes da base."],
                    ["Quais riscos, recomendações ou conclusões aparecem nos arquivos?"],
                ],
                inputs=pergunta,
            )

    importar_drive_btn.click(
        fn=importar_pasta_drive,
        inputs=pasta_drive,
        outputs=status,
    )

    adicionar_btn.click(
        fn=adicionar_documentos,
        inputs=arquivos_upload,
        outputs=status,
    ).then(
        fn=lambda: None,
        inputs=None,
        outputs=arquivos_upload,
    )

    atualizar_btn.click(
        fn=status_base,
        inputs=None,
        outputs=status,
    )

    enviar_btn.click(
        fn=responder,
        inputs=pergunta,
        outputs=saida,
    )

    pergunta.submit(
        fn=responder,
        inputs=pergunta,
        outputs=saida,
    )

    limpar_conversa_btn.click(
        fn=limpar_conversa,
        inputs=None,
        outputs=[pergunta, saida],
    )

    nova_consulta_btn.click(
        fn=nova_consulta,
        inputs=None,
        outputs=[pergunta, saida],
    )

    copiar_resposta_btn.click(
        fn=None,
        inputs=saida,
        outputs=None,
        js="""(texto) => {
            const conteudo = typeof texto === 'string'
                ? texto
                : (texto?.value || texto?.text || String(texto || ''));

            if (!conteudo || conteudo.includes('Aguardando uma pergunta')) {
                return [];
            }

            navigator.clipboard.writeText(conteudo);
            return [];
        }""",
    )

    apagar_btn.click(
        fn=limpar_base_confirmada,
        inputs=confirmar_limpeza,
        outputs=[status, confirmar_limpeza],
    )

print("🚀 Interface pronta.")
print(f"📂 Pasta padrão do Drive: {PASTA_DOCUMENTOS_DRIVE}")
print(status_base())
demo.queue().launch(share=True, debug=True)