# -*- coding: utf-8 -*-
"""Challenge Alura Agente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YkrY5xf-rLPGO2pExTE1_YpQoJITpRD
"""

!pip install google-generativeai PyPDF2 python-dotenv

from google.colab import userdata
GOOGLE_API_KEY = userdata.get('Challenge_Alura_Agente')

from google.colab import files
uploaded = files.upload()

import PyPDF2
import io

def extrair_texto_pdf(nome_arquivo):
    texto = ""
    # Se o arquivo for um objeto bytes (como de files.upload())
    if isinstance(uploaded[nome_arquivo], bytes):
        # Use io.BytesIO para tratar como um arquivo em memória
        arquivo_bytes = io.BytesIO(uploaded[nome_arquivo])
        leitor = PyPDF2.PdfReader(arquivo_bytes)
    else:
        # Caso contrário, trate como um caminho de arquivo
        with open(nome_arquivo, 'rb') as arquivo:
            leitor = PyPDF2.PdfReader(arquivo)

    for pagina in leitor.pages:
        texto += pagina.extract_text()
    return texto

# Lista para armazenar o texto de todos os PDFs
textos_dos_pdfs = []
nomes_dos_pdfs = []

# Itera sobre os arquivos carregados
for nome_arquivo_uploaded in uploaded.keys():
    try:
        texto_extraido = extrair_texto_pdf(nome_arquivo_uploaded)
        textos_dos_pdfs.append(texto_extraido)
        nomes_dos_pdfs.append(nome_arquivo_uploaded)
        print(f"PDF '{nome_arquivo_uploaded}' carregado! {len(texto_extraido)} caracteres extraídos.")
    except Exception as e:
        print(f"Erro ao processar o arquivo '{nome_arquivo_uploaded}': {e}")

# Você pode usar a lista 'textos_dos_pdfs' nas suas próximas etapas
# Por exemplo, para concatenar todo o texto:
todo_o_texto_dos_pdfs = "\n\n".join(textos_dos_pdfs)

# Ou, se o agente precisar acessar cada documento individualmente, a lista já estará pronta.

import google.generativeai as genai

genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel("models/gemini-flash-latest")

# Define um limite maior para o contexto, considerando múltiplos documentos
# Gemini 1.5 Flash tem uma janela de contexto de 1 milhão de tokens,
# então 500.000 caracteres é um limite seguro para a maioria dos casos.
MAX_CONTEXT_LENGTH = 500000

def perguntar_sobre_documento(pergunta):
    prompt = f"""
    Você é um assistente especializado em análise de documentos. Responda a pergunta abaixo
    baseando-se APENAS no conteúdo dos documentos fornecidos.

    DOCUMENTOS:
    {todo_o_texto_dos_pdfs[:MAX_CONTEXT_LENGTH]}

    PERGUNTA: {pergunta}

    INSTRUÇÕES:
    1. Responda de forma clara e direta
    2. Baseie sua resposta APENAS nos documentos fornecidos
    3. Se a resposta não estiver nos documentos, diga "Não encontrei essa informação nos documentos."
    4. Cite trechos dos documentos quando relevante
    """
    resposta = model.generate_content(prompt)
    return resposta.text

# Exemplo de uso:
# Vou fazer uma pergunta que pode abranger mais de um documento para testar a nova funcionalidade.
pergunta = "Quais são os principais tipos de análise de dados mencionados e o que é dito sobre recomendações de governança de IA?"
resposta = perguntar_sobre_documento(pergunta)
print("📝 Resposta:")
print(resposta)

print("💬 Faça perguntas sobre o PDF (digite 'sair' para encerrar)")
while True:
    pergunta = input("❓ Você: ")
    if pergunta.lower() == 'sair':
        print("👋 Até logo!")
        break
    print("\n🤔 Processando...")
    resposta = perguntar_sobre_documento(pergunta)
    print(f"\n✅ Resposta: {resposta}\n")
    print("-" * 50)